### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by alxjsn** [nextcloud/passman-android#12]
Hi,

Are there any plans to get this app on F-Droid?

Thank you!

**Comment by animalillo** [comment]
I sadly don't think our build process is compatible with the way f-droid requires apps to be published, but once it's stable we will certainly look at it, or even provide our own f-droid reppo in the worst case.

**Comment by rugk** [comment]
Actually it should always be possible unless you use some proprietary components (which would be an ugly thing anyway) or so.
This issue is the [most upvoted, thus mostly requested, issue](https://github.com/nextcloud/passman-android/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) in this repo, so please make it happen soon… I think many users would like to use this app on Android and Google Play is just unsuitable for them.

**Comment by animalillo** [comment]
I've took the time to take a fast little look into this this weekend but looks quiet complicated, or at least requires a lot more time looking for info than i expected. If anyone has some experience with this sort of things, their help will be very welcome on this matter.

The other option would be setting up our own repo and uploading there the apks but does not look like the best solution.

We currently have other features to prioritize on the whole passman ecosystem, like whole vault sharing, or making the app also save changes.

So as much as I'd like to get deeper into this I can't right now

**Comment by mimi89999** [comment]
@animalillo Could you please add git tags for releases?

**Comment by animalillo** [comment]
I will, when we are out of alpha ;·)

**Comment by animalillo** [comment]
We could easily provide an apk in our official page if you prefer that to play store, currently adding support for fdroid is far from my priorities

**Comment by animalillo** [comment]
I will welcome any help on this matter, tho!

**Comment by marcelklehr** [comment]
There is already a ticket open on fdroid's side: https://gitlab.com/fdroid/rfp/issues/199

**Comment by marcelklehr** [comment]
Cross-posting this from f-droid's gitlab:
> Cannot create directory /usr/local/ssl: Permission denied
Makefile:639: recipe for target 'install_docs' failed
make: *** [install_docs] Error 13
> ...
> > Refering to that error, it can be safely ignored
> It's fatal, ./SetupOpenssl.sh bails out with non-zero code.

**Comment by marcelklehr** [comment]
Oho, turns out this has already been fixed.

**Comment by animalillo** [comment]
Thanks!

**Comment by jreybert** [comment]
@animalillo is there any update about providing an apk on the website?

**Comment by robjloranger** [comment]
Any update? This is far out of alpha now.

**Comment by fkraemer** [comment]
@animalillo or @marcelklehr  or @haeckle or who else has some overview: What issues persist today in order to implement this old request? Can we split it up or so in order to push this?

**Comment by m-boyd** [comment]
> There is already a ticket open on fdroid's side: https://gitlab.com/fdroid/rfp/issues/199

There's also a new issue opened from four weeks ago: https://gitlab.com/fdroid/rfp/issues/1130

With the new one, the only checkbox remaining is "The original app author has been notified (and supports the inclusion)."

**Comment by Eurbaix** [comment]
If F-Droid is an issue, can it be made available on UpToDown (https://en.uptodown.com/).
Although it is not an App Store dedicated to open source, at least it doesn't depend on gmail account and it's "reasonably" curated.

Worst case scenario, at least an APK on SourceForge would help (with an SHA256 on GitHub to make sure the APK on SourceForge has not been tempered with).

The whole idea of Passman is to get away from cloud providers who take away our privacy. Having to give away everything we do on our phone to be able to get the Android app for Passman defeat the entire purpose of Passman-Android.

Seriously, that should be the most critical issue (it's already the most upvoted). There is no feature more important than being able to use Passman-android without a gmail address (otherwise, we might as well use Google Password manager).

**Comment by CATER-COM** [comment]
Any news ? Passman is one of the most important Android app and the only one not available on F-Droid 😕. Completely agree with @Eurbaix 👍

**Comment by IzzySoft** [comment]
Quoting myself from the already mentioned [F-Droid RFP](https://gitlab.com/fdroid/rfp/-/issues/199) (unanswered for 4 months already):

> I still only see the old tag from 9/2017 in your repo.

Without up-to-date tagging, the app cannot make it to F-Droid. With up-to-date tagging and APKs attached, I could add it to [my repo](https://apt.izzysoft.de/fdroid) in a few minutes (provided it meets the other requirements and isn't larger than 30M).

**Comment by skewty** [comment]
It's for reasons just like this that so many people just gave up and moved over to [Bitwarden](https://github.com/bitwarden).

**Comment by IzzySoft** [comment]
As you still seem undecided for almost 4 years now, please let me ask for a last time: Are you still interested in inclusion with F-Droid? If so, could you please ass [Fastlane structures](https://gitlab.com/snippets/1895688) (at least for `en-US` summary + description) and start tagging your releases? Else we rather give up and close the RFP. Makes no sense to establish a "zombie" that never gets updated.

**Comment by binsky08** [comment]
Hello @IzzySoft, I am currently updating the app and equipping it with new functions and security mechanisms. In the course of this time I hope to be able to add F-Droid support after consultation @animalillo

**Comment by IzzySoft** [comment]
Thanks, @binsky08 – let us know then when we should take a look again!

**Comment by binsky08** [comment]
Hi @IzzySoft, it's time to take another look. We have done a lot of work for the app and just released v1.1.1 :)

**Comment by IzzySoft** [comment]
Yes, and thanks to your work I've added Passman [to my repo](https://apt.izzysoft.de/fdroid/index/apk/es.wolfi.app.passman) a few days ago :wink:

Your current [RFP is here](https://gitlab.com/fdroid/rfp/-/issues/1130) and waiting for you to establish [Fastlane structures](https://gitlab.com/snippets/1895688) here in your repo.

**Comment by binsky08** [comment]
Finally, we got it :)
https://f-droid.org/de/packages/es.wolfi.app.passman

**Comment by IzzySoft** [comment]
Congrats! With the app now in the main repo: do you want me to keep it in mine – or shall I remove it after the usual overlap of ~10 days? Some "decision help" is [available here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ).
