### ISSUE TITLE
cant log in to my vault

### ISSUE THREAD

**Issue by grochib** [nextcloud/passman-android#122]
Hey, 

I just started using passman on Nextcloud (22.2.5 on Docker compose, no newer version available yet) and my first trial with the app went great. 
I was able to install the app, log in with the specifically created app-password (i'm using 2fa) and open the vault with the credentials I set it up with. 
Then today suddenly I could not open the vault from within the app anymore: I was able to start the app, the vault was visible but when trying ot access it the app said: wrong password. I tried from within my nextcloud webpage: it worked just fine. I tried open the nextcloud on the same android phone (using mobile network, not wifi): again I could log in to my vault without problem. 
I tried so far: 
- restart the phone
- reinstall the app from playstore
- reinstall the app from f-droid
- change the password of the vault (both a stronger password but also a shorter, easier one - just "good")
- logging out from any instance before trying to log in on the app

Each time the same error appears, see here:
![Screenshot_20220321-121218](https://user-images.githubusercontent.com/55094750/159252026-886024ba-6f72-466e-8472-edad5f57957f.jpg)
 
I'm a bit lost. Can anybody give me a hind on where I might do smtg wrong? thank you so much!

**Comment by binsky08** [comment]
Hmm, have you tried to write the password in a plain text field of an other app and copy & paste it into the password field? (just to be sure it is no typing error)

May I sould add a password/plaintext toggle button xD

**Comment by grochib** [comment]
Thank you so much for the quick reply!

I tried that one as well, each time with every password.
Is there a cache to be deleted before trying it with a new password?

Or do you know of a way of debugging the communication between the app and
my nextcloud?

Timo Triebensky ***@***.***> schrieb am Mo., 21. März 2022,
15:13:

**Comment by binsky08** [comment]
Unfortunately I could not reproduce the problem

**Comment by binsky08** [comment]
could not reproduce
