### ISSUE TITLE
Network error :(

### ISSUE THREAD

**Issue by vincegre** [nextcloud/passman-android#13]
Hi

Installed Passman on my OnePlus 3 (Android 7.1.1) from Play Store. I get a network error when I try to connect at my NextCloud account !
If I don't put https in front it complains incorrect url so I putted https://monserveur and my credentials but I always get a Network error !
Tested with cellphone connected to Wifi !
Something to try or test ?

Thanks

**Comment by animalillo** [comment]
@vincegre is that the url you entered to the app? If so, it's not a fully quallified domain name, and the phone can't resolve it.

**Comment by vincegre** [comment]
no no it was just not to reveal real url but sure my server is publicly avalaible on internet and with a full FQDN and SSL protection !
I have no problem with other apps on my phone that synchronise to my NextCloud system !

**Comment by brantje** [comment]
Is nextcloud installed in a subdirectory?

**Comment by vincegre** [comment]
nope but SSL is done with a Let's encrypt certificate and I know some old apps don't like much these certificates ! Maybe it's the problem ?

**Comment by animalillo** [comment]
Denepnding on your android version and your server ssl configuration this could be an issue.

@brantje we need an issue template for this project too

**Comment by animalillo** [comment]
Would need more info to debug this out.
Please tell me your:
1. Server port
1. SSL server configuration
1. Owncloud / Nextcloud install path relative to site root
1. Android version
1. Passman version
1. Owncloud / Nextcloud version
1. Server logs (apache and nextcloud)
1. Does the official standard nextcloud/owncloud app works with the device?

**Comment by zmbcgn** [comment]
Sure:

1. 443
2. https://pastebin.com/SbvQQzxw
3. Sites Rootdirectory
4. 7.1.1
6. 12.0 beta2
7. The connection attempt from the app is neither shown in the nginx nor in the nextcloud logfile.
8. Yes. Maybe worth noticing that I also use the TOTP Plugin of Nextcloud.

**Comment by vincegre** [comment]
Here are details requested:

Server port is on standard SSL 443 (only SSL, if it tries http it's automatically redirected to https
SSL server configuration is pretty standard (Apache 2 with Let's Encrypt certificate), has no problem with other cellphone apps that connect at my Nextcloud server

Apache 2 with TLS 1.2

NextCloud installed at root of web server

Android 7.1.1 (One Plus 3)

Passman version on Android: 0.12-NIGHTLY

NextCloud 11.0.3 Passman app: 2.1.2

For logs not sure what you need as logs files are so big :(

No problem to connect with official NextCloud app and some other apps that goes with NextCloud. I use TOTP but I generate a specific distinct password for each app that needs to connect to NextCloud.

**Comment by florianaudon** [comment]
Hi,
I had the same issue on my old android.
I solve it by putting the same certificate on my root server and on the subdomain where I host nextcloud.

Is it possible for you to try?

**Comment by animalillo** [comment]
Maybe it's an issue with old android versions and ssl SNI.

I will have to further investigate this and see if the lib we use for http/s requests has a workaround for this.

**Comment by vincegre** [comment]
@florianaudon  not relevant as I'm in latest version of Android so it has no problem with SNI ! Side note your explanation about your problem looks like your SSL chains were incomplete on your webserver which can cunfuse some browsers !

**Comment by brantje** [comment]
It's also possible that some cyphers are not supported by Android and thus giving problem.
Since the demo server seems to work with Android i'll post the config here for testing purposes
```
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
ssl_ecdh_curve secp384r1;
ssl_session_cache shared:SSL:10m;
ssl_session_tickets off;
ssl_stapling on;
ssl_stapling_verify on;
resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 5s;
# Disable preloading HSTS for now.  You can use the commented out header line that includes
# the "preload" directive if you understand the implications.
#add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;

```

**Comment by brantje** [comment]
You're also having this issue with passman (see https://github.com/nextcloud/passman-android/issues/13), might be a server issue then.

**Comment by nado** [comment]
Hi, I have the same issue on an old phone.
Android 4.4.2 (Wiko Goa)
Passman-android version 0.12 nightly.
LetsEncrypt certificate
My nginx config : 
```
ssl_protocols TLSv1.2;
ssl_prefer_server_ciphers on;
ssl_session_timeout  5m;
ssl_session_cache    shared:SSL:1m;
ssl_ciphers HIGH:!aNULL:!MD5:!3DES:!CAMELLIA:!AES128;
ssl_dhparam /etc/ssl/certs/dhparam4.pem;
add_header X-XSS-Protection "1; mode=block";
add_header X-Frame-Options DENY;
proxy_hide_header X-Powered-By;

add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; ";
```

**Comment by animalillo** [comment]
please, refer to this table as of android support for ssl cyphers:
https://developer.android.com/reference/javax/net/ssl/SSLSocket.html

**Comment by nado** [comment]
Can it be a lack of TLS 1.2 support if I can access the very same url on the stock browser, nextcloud and davdroid application ?
Feel free to ask any detail about my configuration, I dont know what you need. Can it be LetsEncrypt related ?

**Comment by animalillo** [comment]
hmmm maybe the CA from letsencrypt is not included by default in android?

**Comment by brantje** [comment]
Just found this link: https://community.letsencrypt.org/t/android-doesnt-trust-the-certificate/16498

**Comment by vincegre** [comment]
@animalillo If you are using Android 4.4.2 with SNI on your web server it won't work as that version of Android was not compatible with SNI protocol so either update the very outdated Droid or move your server to a dedicated IP for the virtual server....

**Comment by nado** [comment]
@vincegre I suppose you wanted to talk to me as I was the one with a 4.4.2 Android.
If SNI doesnt work, shouldnt it fail for *all* attempts to connect to my nextcloud instance ?
Also according to https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=4.4.2 it should support SNI.
I am open to the fact that it might be my Android version which is too old but I am trying to understand why it succeeds to connect to my server on stock browser or other apps and not for passman.

**Comment by animalillo** [comment]
some apps have implemented workarounds for android flaws, some have not, we have not, we let a library handle that

**Comment by nado** [comment]
I see, I can’t afford a new IP right now and there’s no update above KitKat for my phone.
Anyway thanks for the help. :)

**Comment by vincegre** [comment]
@nado yep it was for you ;) Did you check that your Nextcloud instance has a complete SSL chain with sslabs ?? as it's often a problem if CA certificate is missing ! Full cert chain as you can see below:
![selection_002](https://cloud.githubusercontent.com/assets/3164888/26196008/d91b5e20-3bbd-11e7-8f6f-0357cfafc772.png)
For upgrade of your phones have you checked alternative ROMs ? often better than original ones included by manufacturer of phone :D

**Comment by nado** [comment]
Its a phone too cheap to get attention and get a ROM, I once tried making one but I dint have enough time to focus on it.

SSLabs screenshot :
![chaincert](https://cloud.githubusercontent.com/assets/750258/26196907/b3b1a33a-3bc0-11e7-8341-71e57aebdc54.png)

**Comment by vincegre** [comment]
@nado looks like your only solution now is to change your phone :(

**Comment by animalillo** [comment]
i could check if it's an app problem if you crate me an account and i can try the app on your server from my phone pm me @wolfi on telegram

**Comment by nado** [comment]
I am not on telegram, I still use mails (nado@troglodyte.be), irc (nado on freenode) :)

**Comment by animalillo** [comment]
@nado i sent you an email from marcos@[domain].es

**Comment by brantje** [comment]
Confirmed that android 4.4.2 seems to have issues with some ssl configurations, think on making a workaround or a more descriptive message

**Comment by zmbcgn** [comment]
Based on your answers I made some changes to my nginx configuration, but i still get an network error on my android 7.1.1.

According to SSL Labs i get an A+ on the self test. And I don't want to reduce the security of my website to get the passman app working.

https://www.ssllabs.com/ssltest/analyze.html?d=cloud.5711.org&s=46.163.113.231

**Comment by adocampo** [comment]
Same here, 

Android 7.1.1
Passman: 2.1.2
Nextcloud: 12
SSL: https://www.ssllabs.com/ssltest/analyze.html?d=malevolent.bofhers.com
Dockerized Nextcloud, with the port 443 exposed to the host and directly published. No other problems with other nextcloud services noticed.

**Comment by animalillo** [comment]
@adocampo are you specifiying https protocol? Using subdirectories? How are you typing the url? Maybe that helps us get the error.

**Comment by adocampo** [comment]
Yes, the URL is https://malevolent.bofhers.com/nextcloud (I tried both with an ending slash and without it). I did use succesfully the android app back when I didn't implementedyet the LE certificate and I could access the server with a selft-signed certificate.

**Comment by animalillo** [comment]
I'm going to try and check what's going on there @adocampo.
Would it be possible to get an account to login to passman and try this out with your setup?
If you want to keep a faster communication I'm @WolFi in telegram.

**Comment by animalillo** [comment]
So far, i've tried this, and it, unsurprisingly gives me a 401 unauthorized, so... i don't see any ssl errors there (android 6) 

![imagen](https://user-images.githubusercontent.com/3353109/28491356-08b4e308-6ef0-11e7-8ac0-95e067c16f5d.png)

**Comment by adocampo** [comment]
I've just contacted you via telegram, I'm going to create an account for you to see if we can reproduce the issue.

**Comment by adocampo** [comment]
Solved. As I connected to the server with a self-signed certificate and changed to Let's Encrypt one, somewhere on the cache probably was the old one thus it didn't match the new one.
Deleting the app cache solved the problem 👍

**Comment by zmbcgn** [comment]
Well, not for me. Meanwhile I have a brand new phone with an official android version 7.0 (no lineage or cyanogen etc.) and I wiped the app cache. Still getting an network error message.

If neccessary I can create you an test account as well.

**Comment by animalillo** [comment]
that would be niec, @zmbcgn. you can pm me on telegram if you wish @WolFi there.

**Comment by zmbcgn** [comment]
Credentials sent via telegram.

**Comment by zmbcgn** [comment]
Maybe also worth mentioning, that I dont have any issues with the web-extension of passman (https://github.com/nextcloud/passman-webextension/).

**Comment by animalillo** [comment]
didn't got any telegram at WolFi

**Comment by zmbcgn** [comment]
now maybe?

**Comment by animalillo** [comment]
Yes, now i notice you sent it on a private message which i don't get on the desktop app xD
I will try to connect to your server this afternoon and tell you what i can find.

**Comment by nicman23** [comment]
same here, passman webextension, and the website frontend works fine.

however i believe this is just because i am running it on very very low hardware and it just gets timeout

if you care to test my server also the url is home.nicman23.tk i shall make a test:test acount

**Comment by animalillo** [comment]
I have published a new alpha release. It seems to fix network issues on some devices and it has more descriptive network errors.

Please, tell me if the new version released on the store fix this problem.
Also note, it might take a few hours for google to process and propagate the update, so please, make sure you are running v0.13 Nightly before saying it does not work.

**Comment by nicman23** [comment]
my issue seemed to be a missing chain key from apache.

**Comment by adocampo** [comment]
I can also connect now to my server. 👍

**Comment by AnisKhanUK** [comment]
Hello, I have a Nexus 6p which just got upgraded to Android O.

The app was working before the upgrade from 7.1.2.

I am on the latest nightly but am getting 'Settings incorrect'

Any ideas?
Thanks

**Comment by animalillo** [comment]
probably wrong username/password. double check url, user and password are correct. I would need more info to help you @AnisKhanUK.

**Comment by AnisKhanUK** [comment]
You were right - I needed to use my APP password as I had setup 2nd factor authentication.

Brilliant.

**Comment by animalillo** [comment]
After watching it for a few days, I think it's safe to close this issue! If anyone finds any trouble with this, i will try my best to help them debug it!

Closing! :D

**Comment by icebrian** [comment]
I am currently experinecing this same problem on Android 6.0.1. Certs have been generated with let's encrypt, everything works fine through browser, including on Android and laptops, but via app I get a handshake failed error message.

On ssllabs.com I have a B rating with handshake simulation only failing on android 2.3.7 with a "No SNI" message. All other version pass as green.

I am also using nginx and I have tried using the configurations above but to no avail I have also cleared apps cache but still same problem.

Any ideas?

**Comment by jzielke-nli** [comment]
@animalillo Unfortunately I'm having the same problem.

I'm using latest passman app on nextcloud 13 from this repo and the android app on my galaxy s8.

The chrome extension runs just fine but on android using an app-password because of 2factor auth I get network error after entering my https-url and my credentials. However I see my password safe being displayed, just can't open it.

**Comment by brantje** [comment]
We got reports of @jzielke-nli having trouble, reopening.

**Comment by animalillo** [comment]
following the conversation from #49 here
@jzielke-nli, you could pm me the connection details and credendials vía [telegram](https://t.me/wolfi) and I could take a look into your issue

**Comment by jzielke-nli** [comment]
@animalillo Thanks for offering that. I'll send you some credentials and keep the communication up here as requested by @brantje in #49 .

**Comment by jzielke-nli** [comment]
@animalillo Any progress on your debugging efforts?

**Comment by animalillo** [comment]
didn't have time to check it out yet! will try to this week or at least this weekend! Sorry for the delay, i have recently moved to a new home and things are a little fuzzy yet

**Comment by jzielke-nli** [comment]
@animalillo How can I debug this on my android device?

**Comment by xXSTrikeXx** [comment]
@jzielke-nli google for adb logcat ;) In nextcloud-android on the startsite there is a small description ;)

**Comment by jzielke-nli** [comment]
Confirmed on my device:

```
03-08 15:30:04.114 27576 27576 E android.nfc.Tag$1@d4f9e29: Unknown network error
03-08 15:30:04.114 27576 27576 E android.nfc.Tag$1@d4f9e29: org.json.JSONException: No value for favicon
```

**Comment by animalillo** [comment]
yeah, seems that @brantje changed the field name on the api response on the version you have and that's the problem, if I have time on what is left of the week I will try to release a fix and maybe add a server version check.

**Comment by jzielke-nli** [comment]
Is the favicon really necessary? I can't remember having seen in any part of the app. So why not removing this one rather than implementing a fallback routine?

**Comment by binsky08** [comment]
with the new version [1.0.0](https://github.com/nextcloud/passman-android/releases/tag/v1.0.0) a lot of code has changed.
since nothing has happened here for a long time, I would close the issue soon if the problem does not still exist

**Comment by vincegre** [comment]
I'm closing it as I don't use passman since few years and no one else has reported same issue ;)
