### ISSUE TITLE
Login doesn't appear to do anything

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [nextcloud/passman-android#135]
I attempt to login but nothing appears to happen. I've never used passman, so it might not be installed on my instance. If that's the failure I would expect a helpful failure message.   ![Screenshot_20220706-164942_Passman.jpg](https://user-images.githubusercontent.com/65328167/177650284-379bde5d-18e9-414e-8ce4-73885461389a.jpg)

**Comment by binsky08** [comment]
I'm sure the missing Passman Nextcloud app is the problem.
