### ISSUE TITLE
Implement transifex for translations

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman-android#14]
Would be nice to have the app in different languages.
cc @MorrisJobke

**Comment by MorrisJobke** [comment]
Could you point me to the file(s) that contain the english source strings? See  https://github.com/nextcloud/android/blob/master/.tx/config#L6 for the location in our Android app.

**Comment by brantje** [comment]
Source file is located at: https://github.com/nextcloud/passman-android/blob/master/app/src/main/res/values/strings.xml

**Comment by brantje** [comment]
Thanks! =D

**Comment by MorrisJobke** [comment]
Let me trigger it and then it should run every night around 2/3 UTC.
