### ISSUE TITLE
Translation broken

### ISSUE THREAD

**Issue by obimichael** [nextcloud/passman-android#149]
In German I only see the following text: Benötigt keine Übersetzung.  Hier wird nur die formelle Übersetzung verwendet. (de_DE)
I tried to find to change to English, but with no luck.
Version: 1.4.0-gplay

**Comment by binsky08** [comment]
Hi @obimichael, wo genau siehst du denn diesen Übersetzungsfehler?

**Comment by obimichael** [comment]
Hallo, einfach überall wo ein Text stehen sollte und keine Daten. Anbei exemplarisch ein Bild von den Einstellungen

![configuration-passman-android](https://user-images.githubusercontent.com/4639665/196046996-e6881af0-d2b1-4590-95b8-b6cd6a00904d.jpg)

**Comment by binsky08** [comment]
Hi @rakekniven you do things with translation and transifex for nextcloud projects, right?
It seems that Transifex does strange things and has moved some translation, for example, from the "values-de" folder to "values-de-rDE". This then apparently ends in these strange representations in our current release ^.
See this example: https://github.com/nextcloud/passman-android/blob/15970c51e17388f2c551a2576f603fddbdbab920/app/src/main/res/values-de/strings.xml

Any idea what we can do to fix that?

**Comment by nickvergessen** [comment]
There was a temporary error, that lead to the assumption a workaround we had in place is not needed anymore.
We reverted back to the workaround today and it fixed the Nextcloud files and talk clients already. All other apps should follow tonight.

I tabbed the sync of this app manually for now.

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/docker-ci/pull/450

**Comment by nickvergessen** [comment]
Back again: https://github.com/nextcloud/passman-android/commit/4b144110b943b14a6f7f2a6ae05545a09c022788

**Comment by nickvergessen** [comment]
It already did sync, so yeah?

**Comment by obimichael** [comment]
@binsky08 thanks for your help! 

My default Language is "German (Austria)" [Deutsch (Österreich)] , if I change to German (Germany) [Deutsch (Deutschland)] it is working correct. If i change back to "German (Austria)" I only see the text as you see on the Screenshot.

**Comment by obimichael** [comment]
@rakekniven With language "German Swiss", it looks like the same as with "German Austria".

**Comment by binsky08** [comment]
should be fixed with [v1.4.1](/nextcloud/passman-android/releases/tag/v1.4.1)
