### ISSUE TITLE
replace Donate on fdroid metadata, flattr is error 404

### ISSUE THREAD

**Issue by ghost** [nextcloud/passman-android#158]
* **your explicit consent is required** to replace Donate ```https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=6YS8F97PETVU2``` with ```https://passman.cc/#donate``` in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/HEAD/metadata/es.wolfi.app.passman.yml)
* Flattr ```https://flattr.com/@passman``` is error 404 given at https://github.com/nextcloud/passman-android#support-passman _is it replaced or deleted?
* fdroid [policy](https://gitlab.com/fdroid/admin/-/issues/417), [discussion 1](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549#note_1508711371) and [discussion 2](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13533#note_1504648422) wrt to adding AuthorEmail, AuthorWebSite, Donate, etc..

**Comment by binsky08** [comment]
I think removing bitcoin and paypal donations from the Passman fdroid metadata is fine, by replacing it with just https://passman.cc/#donate.
