### ISSUE TITLE
Automatically prepend https:// if no protocol is defined on login

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/passman-android#16]
When setting up an account it should be possible to just enter the cloud URL without a protocol handler.

**Comment by animalillo** [comment]
I don't think it's a good idea, it might be an ftp account, or an ssh ip, or a lot of other non-related to web stuff that the user rather has without the protocol specified on the url.

If you do copy-paster you should take care of the protocol if you care about it IMHO.
What do you think @brantje ?

**Comment by juliushaertl** [comment]
I was talking about the login screen of the android app, not the password entries. Sorry for being to vague about that. :wink:

**Comment by animalillo** [comment]
oooh! right! sorry! i'm too tired and did not check which passman repo i was answering into xD
Then yes! it's a good idea to prefill "https://" into the field!

**Comment by comradekingu** [comment]
How about just serving it with "https://" already filled in.
If you for some reason need http://, it is just the one letter to remove.

**Comment by AndyScherzinger** [comment]
I'd say just do it like the Nextcloud client. If no protocol is given in he string try calling https if that doesn't work try calling http. 
Any prefilling of the field is bad, because if the user doesn't have https then they need to change it. We not let the app do all the guess work trying out the options? ;)

**Comment by animalillo** [comment]
since this is solved but not yet released, i'm closing the issue.
solved with merge #22
