### ISSUE TITLE
App allows vaults to be created without password

### ISSUE THREAD

**Issue by johnkiddjr** [nextcloud/passman-android#160]
Went to create my first vault after installing the Android app, and left the password blank, figuring I'd go back and add one once I was sure I was going to be able to move all my passwords over. This worked and created a new vault.

But when I tried to get into the vault, it wouldn't let me in without a password and just says "Wrong Vault Password".

I then tried to delete the vault, but I can't do that either without the password, so I clicked forgot password and requested deletion... which has to be done by an admin. I'm an admin, but I can't find any admin settings for PassMan in NextCloud... so not sure if that doesn't work either, or I just can't find it.

**Comment by binsky08** [comment]
Hi @johnkiddjr, thanks for the pull request. I was stupid and didn't think to check for an empty password.

We already have an issue about that vault deletion request stuff here: https://github.com/nextcloud/passman/issues/801.
Maybe I'll implement an option to disable this "feature" at some point. It annoys me a bit too :D

You should find it in the Passman subsection of the "Additional settings" section in your Nextcloud administration.
See https://github.com/nextcloud/passman/issues/416#issuecomment-350500139

**Comment by johnkiddjr** [comment]
Hi @binsky08 thanks for the info, that's exactly what I was looking for!

And no worries, these things are easy to overlook. Luckily, it was an easy fix too!
