### ISSUE TITLE
Next Version

### ISSUE THREAD

**Issue by beli3ver** [nextcloud/passman-android#18]
Hi,
I want to know, when the next version will be released?
Do you still working on this project?

**Comment by vincegre** [comment]
Looks like project is dead :(

**Comment by beli3ver** [comment]
Yeah.
That's the reason I switch back to pass

**Comment by vincegre** [comment]
Pass ??

**Comment by beli3ver** [comment]
https://www.passwordstore.org/

**Comment by brantje** [comment]
Project dead? Are you insane? In numerous issues we keep telling users we have our lives + our 40 hour day jobs. Next to that we also have the web extension and the normal app.

**Comment by animalillo** [comment]
No, we hadn't forgot about this project, we are just too busy with life and main passman application features.

We would love to be able to work exclusively for passman, but, unfortunately it does not provide enough income for this.

Stop forbid us to don't have the time and energy to keep three projects updated every day with new awesome features.

I would review any merge request if you, or anyone is willing to help with the project.

**Comment by vincegre** [comment]
@animalillo I would be very happy to help in any way I can (I can offer translation service english/french, french/english, test of dev versions, I do programming too (but on specific systems) so not sure I can help here in that domain....

**Comment by brantje** [comment]
@vincegre Sorry if i sounded harsh. Saw those comments before my first cup of coffee. My excuses, 
We use Transifex for managing translations if you sign up with you github account at 
https://www.transifex.com/nextcloud/nextcloud/passman/ then i'll take care of the rest.

**Comment by animalillo** [comment]
And if you are willing to help with the code parts of the android app, webextension, or nextcloud app feel free to tell us! Currently the part we would need more help for the android app is the encryption part (which is c/c++ and openssl) because it might look small but it's a headache to implement.

**Comment by vincegre** [comment]
@brantje don't worry, no problem and I fully understand your reaction ;) my account on transifex is vincen !
@animalillo well encryption is probably not the best place to start participating in project as it looks pretty complex and not really familiar with mobile app. If it's ok I would prefer to focus on webextension ;) Is there some sort of basic tuto or explanations on rules and how to participate in project for coding ? (need to learn how to use correctly git too....

Thanks you two for help ;)

**Comment by beli3ver** [comment]
My name is maltekiefer I want to translate to german.
Could you add me.
Sorry for my reaction...

**Comment by brantje** [comment]
Register on transifex, after that go to https://www.transifex.com/nextcloud/nextcloud/dashboard/
You will see something like this
![image](https://user-images.githubusercontent.com/2758767/28861980-a16a7e66-7763-11e7-8f91-40735ac711b9.png)
On the right, click join team.

**Comment by vincegre** [comment]
@brantje Thanks ;) joined the team on transiflex and will keep an eye regularly if some strings need to be updated in French !

**Comment by animalillo** [comment]
I have published a tiny update today.

**Comment by animalillo** [comment]
Next release plan is on issue #24, i'm closing this question.
