### ISSUE TITLE
Save new passwords on Android App

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/passman-android#19]
Hello,

is it possible to add an function to add passwords to the Wallet?

**Comment by animalillo** [comment]
Yes, in the future it will be possible. We still need to figure out the way to encrypt items, but once we manage to do that adding and editing will be easy

I wish i had more free time to finish the app.

**Comment by Happyfeet01** [comment]
Any new update?

**Comment by brantje** [comment]
No update. We have real lifes too you know ;)

**Comment by Happyfeet01** [comment]
Sure

**Comment by DJaeger** [comment]
I placed a $10 bounty on [Bountysource](https://www.bountysource.com/issues/47257015-save-new-passwords-on-android-app)

**Comment by animalillo** [comment]
Should be resolved with https://github.com/nextcloud/passman-android/releases/tag/v1.0.0
