### ISSUE TITLE
typo: Nextloud credentials

### ISSUE THREAD

**Issue by pdurbin** [nextcloud/passman-android#2]
https://github.com/nextcloud/passman-android/blob/af2e50648f5b22da23fca3e83634a5883ad541d6/app/src/main/res/values/strings.xml#L10 says "Please enter your ownCloud / Nextloud credentials" and I assume this should say **NextCloud**. I noticed this at http://imgur.com/a/hNkuM via https://github.com/opensourcedesign/jobs/pull/169

**Comment by jancborchardt** [comment]
Heya @pdurbin, cool to see you on here! :) It is in fact called »Nextcloud« with only the first N capitalized. ;)
