### ISSUE TITLE
Clean clipboard automatically

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-android#20]
I would like the app was able to clean the clipboard password in X seconds, configurable through app settings, or just long pressing the copy button, a pop up letting choose how many seconds do you want to have it in the clipboard (like 10, 30, 60, unlimited, and by default 30s).
I think its a tiny change and improves the security greatly if there is someone near peeping.

**Comment by comradekingu** [comment]
Wouldn't that make peeping more effective, since the pass needs to be entered more often?
Though it guards better against physical takeover, i'm not quite sure what is suggested.

**Comment by animalillo** [comment]
Hmm i don't know if this is possible, i could look into it of course.

My main doubt is about the menu for the time, i don't want the interface of the view more boosted than it already is. Maybe making it a global preference for all copied items?

I guess this feature will have little sense once the keyboard part is implemented, but that would be way more complicated to implement i think.

**Comment by adocampo** [comment]
@animalillo if a keyboard is planned, that should be even greater, but if you think cleaning clipboard can be uselful in the meanwhile, that should do the job perfectly. You can even make a checkbox "clean the clipboard in 30secs" for people like me who thinks the clipboard is a security flaw or be disabled for the people who thinks the opposite. ;)
