### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-android#21]
Please [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) your [releases](https://help.github.com/articles/about-releases/), so they can be seen [on GitHub](https://help.github.com/articles/creating-releases/).

**Comment by brantje** [comment]
This is also a requirement for [f-droid](https://gitlab.com/fdroid/rfp/issues/199#note_34967983)

**Comment by nado** [comment]
https://github.com/nextcloud/passman-android/issues/12#issuecomment-313664248

**Comment by animalillo** [comment]
Tagged latest release, keep in mind passman for android is in alpha status.
https://github.com/nextcloud/passman-android/tree/v0.13

**Comment by rugk** [comment]
Thanks!
