### ISSUE TITLE
Passman seems to show deleted credentials

### ISSUE THREAD

**Issue by IBBoard** [nextcloud/passman-android#23]
I went to use Passman on my phone today and was confused to find old dummy credentials from Keefox in there. I was sure I'd deleted them.

On checking the web interface, I found that they were in the "Deleted Credentials" bin.

I clicked each credential, clicked "Destroy", and then closed and re-opened Passman on my phone. It now doesn't show those dummy credentials.

My guess is that Passman (or maybe the API it uses?) isn't differentiating between deleted and available credentials.

**Comment by animalillo** [comment]
hmmm probably not taking the deleted tag into account, i'm adding this for the next release as this should be easy to implement.
