### ISSUE TITLE
To do for V0.14

### ISSUE THREAD

**Issue by animalillo** [nextcloud/passman-android#24]
I plan on adding this for the next big update:
- [x] Search of credentials on merge 31800bf7a3720ad0bc8ca7c2f218e5c0d3f2be07
- [x] Credential sorting done on #37 missing some git fixes that has slipped from some cryptotests i was making on another branch
- [x] HTTP/HTTP protocol picker fixed by merge 7b6153d8a49498f3a39fff5ed86599b60a42cd68

If there is anything you think it's easy to implement and would like to see on the next release, feel free to comment on this issue!

**Comment by brantje** [comment]
Sorting of credentials? By default credential label should be used.

**Comment by marcelklehr** [comment]
Just a reminder: Please don't forget to notify the people over at f-droid about the release, so they can start integrating the app. See https://gitlab.com/fdroid/rfp/issues/199

Thanks :)

**Comment by binsky08** [comment]
@animalillo there is still a open pr related to this issue: https://github.com/nextcloud/passman-android/pull/37
