### ISSUE TITLE
Cant connect to my nextcloud 

### ISSUE THREAD

**Issue by wehrstedt** [nextcloud/passman-android#33]
If I try to connect to my nextcloud I get the following message:
value <! Doctype of type Java.lang.string cannot be converted to JSONArray

Can I use the App or is it Not for public use now?

**Comment by wehrstedt** [comment]
Sorry, my fault. After I disabled the two-factor authentication I was able to connect to my server

**Comment by brantje** [comment]
You need to use an app password.
