### ISSUE TITLE
Sync remove password generated with the extension!!

### ISSUE THREAD

**Issue by floreal797** [nextcloud/passman-android#35]
Hi,

Since I upgrade the extension to 2.0.4 version, when I add a password through the password generator, it appears on the extension menu. But if I go to my nextcloud and I search for it, it's not present. And when I sync passwords, it disappeared from the extension and the password is lost!!

It is not every time, but still often... It's a big and critical bug, isn't it?

**Comment by brantje** [comment]
I think you are in the wrong repo.
The web extension repo is here: https://github.com/nextcloud/passman-webextension
Feel free to open it there.
Closing because this repo is not about the extension.
