### ISSUE TITLE
Error: Socked closed during handshake

### ISSUE THREAD

**Issue by trohrberg** [nextcloud/passman-android#36]
Hello,

after having problems with connecting with the passman app to my nextcloud due to bad SSL configuration, I have a new problem now. The SSL configuration seems to be fixed and is validated by SSLLab.com with grade A. Now the passman app shows the error message "socked closed during handshake" when trying to login. Unfortunately, I don't get any further details about what exactly is going wrong. I just know that connecting to the nextcloud via browser works fine and also the SSL configuration seems correct.

I'm using a phone with Android 4.4.2 and SSLLab.com shows an approved simulation for that version of Android. Also connecting to the nextcloud via chrome browser from the same phone works. The SSL certificates are official Let's Encrypt certificates.

Do you guys have any hint what might be wrong?

Thanks for any hints.
Timo

**Comment by brantje** [comment]
Let's encrypt certificates are known to give trouble because they are not in the android 4.x system
Try importing them to your phone.

**Comment by trohrberg** [comment]
Thank you for your answer. I already had some discussions about that "Let's Encrypt certificates not bing supported on Android 4.x systems" here. However, I still don't completely get it and I would really like to understand the root cause of those problems.

The report (see attachment) returned by SSLLabs.com for my nextcloud installation shows the certification path. On my smartphone, I can see that I do have the "DST Root CA X3" certificate in my trust store already (built-in). So the system should be able to check the certification path, shouldn't it?

Also the report contains the simulation section which indicates that android 4.4.2 systems should work with my nextcloud setup. And with chrome browser on my smartphone I can successfully connect to my nextcloud installation. Why does it then not work with the passman app?
[ssl-report.pdf](https://github.com/nextcloud/passman-android/files/1450362/ssl-report.pdf)

**Comment by brantje** [comment]
Maybe @animalillo can shine some light on this.

**Comment by binsky08** [comment]
outdated. please reopen if the issue persists on current hardware and app version
