### ISSUE TITLE
invalid URL Backend or connexion error

### ISSUE THREAD

**Issue by eliohann** [nextcloud/passman-android#38]
Hi,

I'm currently using a public nextcloud instance at cloud.unixcorn.org for testing purpose before running up my own nextcloud instance.

On this nextcloud instance, passman is active (v2.1.4).
https is on with let's encrypt certificate.

Android official app works fine.

But when i try to set up passman app, it tells me : 
Invalid URL Backend or connexion error.

Can you solve this issue or tell me what information you need to work on it ?

**Comment by animalillo** [comment]
Can you provide the url you are entering in the app after selecting the proper protocol?

**Comment by eliohann** [comment]
cloud.unixcorn.org

Without / in the end ... and without https:// in front (as if i try, it show https://https://cloud.unixcorn.org for url)

I try with end / also and still same error.

**Comment by animalillo** [comment]
Try removing the protocol from your entered text (the https:// part) as it is automatically perpend by the app.

**Comment by eliohann** [comment]
Already done.

As i said, the text i type is : 
cloud.unixcorn.org

That's all

**Comment by animalillo** [comment]
I will try to set it up, without a username and pw this afternoon and tell you something

**Comment by brantje** [comment]
Are you using 2FA?

**Comment by eliohann** [comment]
OK thanks.

I'm not using 2FA

**Comment by git001** [comment]
I have also tried today to login to my hosted passman and got the same error as @eliohann how can I help to debug this issue?

I have selected `https` and used only the `cloud.mydomain.com` with username and password.  
The message is `Wrong Settings

**Comment by git001** [comment]
> The message is `Wrong Settings

The error was [PEBKAC](https://en.wikipedia.org/wiki/User_error).  
I have used the password for vault key instead of the nextcloud login in the first screen.

```
url: <NEXTCLOUD URL>
Login: <NEXTCLOUD User>
Password: <NEXTCLOUD Pass>
```

**AFTER** that task can the vault key selected and **THERE** put the vault password ;-)

**Comment by dersch81** [comment]
I have the same problem with connecting to my cloud. There is also no 2FA login.

**Comment by binsky08** [comment]
closed due to inactivity, was not able to reproduce it in v1.3.1
