### ISSUE TITLE
Shared passwords are not shown

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/passman-android#40]
Credentials shared by another user are shown in the Nextcloud Passman Web Interface, but not on the Android app.

**Comment by animalillo** [comment]
It's not  yet implemented, but will be in the future

**Comment by binsky08** [comment]
duplicate issue #57

**Comment by SIRSteiner** [comment]
I also miss this feature. Are there any news? Many thanks

**Comment by binsky08** [comment]
Thanks for the reminder. I will take a look at it soon.

**Comment by binsky08** [comment]
I was able to implement it today, but until merge and the next release it could take some weeks.

@SIRSteiner If you want to test it in the meantime you can build it from https://github.com/nextcloud/passman-android/tree/feature/shared_credentials

**Comment by wdaskaluk** [comment]
Do you know when this will be available?  The comments suggest it's implemented but I still don't see shared passwords in the android app.

**Comment by binsky08** [comment]
You're right, it is already implemented, but we have to wait for the maintainer and as well its signing key for a new app release.
I'm poking him every two weeks :/

But the signs are good that it will happen this weekend.
