### ISSUE TITLE
Android Oreo Autofill

### ISSUE THREAD

**Issue by Jab2870** [nextcloud/passman-android#50]
Are there any plans to work with the Autofill feature in android oreo?

https://www.blog.google/products/android/use-your-favorite-password-manager-android-oreo/

https://developer.android.com/reference/android/service/autofill/package-summary.html

**Comment by Jab2870** [comment]
I am afraid I am not an android developer. Is this of use? https://developer.android.com/guide/topics/text/autofill.html

**Comment by animalillo** [comment]
This might help, sadly I don't have time right now to implement this feature or any oreo devices to test this on.
I will look on this for a future release when I have some spare time for passman tho! Thanks for the links and I think it's a great feature for android, so expect this to be implemented.

**Comment by wbrawner** [comment]
Hey! I have an Oreo device and would love to see autofill implemented myself. If no one is currently working on this, I'd be happy to take a look myself.

**Comment by violoncelloch** [comment]
As nobody stated so here I think noone is working on this atm, because the main devs are busy...
So give it a try

**Comment by wbrawner** [comment]
Cool, I'll take a look then :+1:

**Comment by kukukk** [comment]
Hi!

I also would love to have this feature and be able to use Passman as a full-featured cross-platform password manager.

I don't have time to develop, but I can help you with some testing on devices running Android 8.0 and 8.1. If the steps for building the app locally are updated I can try to install the app from source and help you with debugging in case I discover any problem. (At least I was able to debug and fix a bug for the Nextcloud Notes Android client)

**Comment by wbrawner** [comment]
I've unfortunately had something come up so I won't be able to look at this any time soon I'm afraid :(

**Comment by HahUK** [comment]
I've been doing some work on this and should have something ready for people to test in the next few weeks. Current status is:

1.) An App can request autofill from Passman and get credentials which match the packageName (e.g. com.justeat.app.uk). The packageName is stored in a custom field within the Credential . This means you can update existing credentials with the packageName and it will link up.

2.) Where no matching credential is found, and the user requests that Android store the credential using the autofill service, a new credential is created and stored in the vault. The label for this credential is the name of the application which called the autofill service (e.g. Just Eat).

3.) Creating a credential required a significant amount of work. I had to write encryption routines compatible with the javascript encryption used in Nextcloud Passman. This needs thorough testing and is very rough around the edges.

4.) This also means that the prerequiste code required to build a "Create Credential" work flow in the GUI is now available however I haven't started looking at it.

5.) Everything is very simple and rough - I haven't developed for Android for years so I need some time to do cleanup of my 2 million Log.d statements.

6.) The autofill currently relies on the autofill hints been available in the target application, no logic has been added to allow the autofill of inputs which do not provide hints. This means web forms will not attempt to autofill. THis will need significant work.

Thanks,

Tom

**Comment by TheBigFatTony** [comment]
Great news, @HahUK !
I also need this feature to fully embrace Passman. Where can we download your fork?

**Comment by TheBigFatTony** [comment]
thanks for your work. i just bought a new laptop and have to reinstall android studio etc, so i require a good internet connection. i may be able to give your a result in 24 h.

**Comment by TheBigFatTony** [comment]
I didn't succeed.
I set the ndk path by simply executing `export ANDROID_NDK_ROOT=/home/username/Android/Sdk/ndk-bundle` before `./SetupOpenssl.sh`. Maybe this was wrong? This is the error I got:

[SetupOpenssl error log.txt](https://github.com/nextcloud/passman-android/files/2744290/SetupOpenssl.error.log.txt)

**Comment by TheBigFatTony** [comment]
I'm getting nowhere. I wanted to run the app in a virtual device (tried: Pixel 2 and Nexus S) but i get
`
    Device supports x86, but APK only supports armeabi-v7a
`
So I tried to send the app to my phone (Xiaomi Mi 5s, Lineageos 15.1, Android 8.1, ARMv8-A), but I got:
`
ABIs [arm64-v8a,armeabi-v7a,armeabi] set by 'android.injected.build.abi' gradle flag contained 'ARMEABI, ARM64_V8A' not targeted by this project.
`

I assume that the native (ndk) code is compiled for `armeabi-v7a` only and that's why it doesn't work on my devices, right? Which device should I try to emulate?

**Comment by morgankevinj** [comment]
Bitwarden's app has this feature and their code for it is at https://github.com/bitwarden/mobile/tree/master/src/Android/Accessibility

**Comment by DJaeger** [comment]
I placed a $20 bounty on [Bountysource](https://www.bountysource.com/issues/57143568-android-oreo-autofill)

**Comment by binsky08** [comment]
Should with https://github.com/nextcloud/passman-android/releases/tag/v1.0.0
