### ISSUE TITLE
Passman no longer on Play Store?

### ISSUE THREAD

**Issue by ahmcuxafei** [nextcloud/passman-android#54]
I have a need to reinstall Passman, but it seems it's no longer available on the Google Play Store. The link from passman.cc returns 'page not found'.

**Comment by Oliv4945** [comment]
Hi, I just tried to install it on a new phone, same error :/
Anything we can do to help ?

Thank you

**Comment by vincegre** [comment]
Neither on f-droid ! Is the project still alive ?

**Comment by violoncelloch** [comment]
It has never been on f-droid...

**Comment by vincegre** [comment]
My mistake :( i thought it had been....well for now it's nowhere in apk so unable to update it !

**Comment by mog71** [comment]
can confirm. passman app is missing in the app store.

**Comment by forresthopkinsa** [comment]
welp, guess I'm not using Passman

**Comment by ahmcuxafei** [comment]
I went with this Bitwarden docker container. It doesn't integrate with Nextcloud, but every other feature more than makes up for it. https://hub.docker.com/r/mprasil/bitwarden/
