### ISSUE TITLE
very problematic issue with otp feature !!!

### ISSUE THREAD

**Issue by vincegre** [nextcloud/passman-android#55]
Hi

Being in travel i use passman version 0.141 on my two android devices and i had the very bad surprise that otp feature is buggy (working for some sites but not all). For the ones not working it generates awrong otp code making it impossible to log on these websites 👎 
Never had that problem with the firefox extension on computer !!

Vincèn

**Comment by binsky08** [comment]
should be fixed with https://github.com/nextcloud/passman-android/commit/71e74194e9f1837434f4778ae73a56e8a523f976
