### ISSUE TITLE
ssl error on new Nextcloud installation

### ISSUE THREAD

**Issue by cheers007** [nextcloud/passman-android#62]
Hi, this is a fresh Nextcloud install on Ubuntu 18.10. I did the Nextcloud install by checking the package on initial Ubuntu install steps. Been a while since I worked with Linux, so bit rusty, I tried installing the cert with certbot, I got the green padlock, and the redirection from http to https worked, but I ended up losing my Nextcloud home page, it was returned to the Apache default page. I finally found that command : nextcloud.occ config:system:set trusted_domains 2 --value=mydomainname.com. While this got the login page back, the redirection doesn't work and browzers complains that the page is not secured, but if I check the details, it does show the letsencript cert. It is probably just a matter of updating settings, but I do not know which file to update. Cheers !

**Comment by cheers007** [comment]
All is fine, I had to update the DNS !

**Comment by cheers007** [comment]
The redirection works fine with Internet Explorer but not with Firefox nor Chrome.

**Comment by ardevd** [comment]
If it's not working with Firefox and Chrome then you're doing something wrong. No sure what sort of redirection you're trying to do but hopefully you've configured an apache virtual host associated with your Nextcloud installation. When accessing your nextcloud instance using a domain name that resolves that wherever your apache instance is running it should direct the requests to the correct virtual host.

I'm serving Nextcloud behind a reverse nginx proxy. The proxy takes care of SSL before redirecting it to the nextcloud VM.

**Comment by cheers007** [comment]
Tks for the comment. I installed nexcloud along with the Ubuntu installer, so everything was automated. But, as I mentioned, it works perfect with IE.
