### ISSUE TITLE
Conect to my Nextcloud not working viia Proxy

### ISSUE THREAD

**Issue by trupf** [nextcloud/passman-android#68]
I need to use a proxy to connect to my owncloud, no matter if I'm connected with an VPN or directly use the company network. While I can connect to my nextcloud with the browser in both szenarions (direct compny network or connection via VPN), I can not connect with passman as long as I use the VPN. I can not see any error messages in passman, it just doesn't show any of my login information. Is there a way to see debug information? Does the extension use the brower proxy settings with all exceptions?

**Comment by binsky08** [comment]
@trupf Is the problem current?
When using the Passman app over a Tor proxy (using Orbot in VPN mode), I can not experience any problems.

**Comment by trupf** [comment]
I'm not more using passsman, I'm now using KeepassXC, which has many advantages, specially Keepass has compatible tools for all platforms I use, not only for the browser.
