### ISSUE TITLE
Passman APP- incorrect settings

### ISSUE THREAD

**Issue by Konderi** [nextcloud/passman-android#70]
Hi, 

I'm having issues with connecting to passman with android app.
I'm using Oneplus 7 Pro, with latest OxygenOS 10.
Nextcloud is running latest version 16.0.5, Passman version 2.3.2

With browser everything works, all other features are fine.
I'm using HTTPS with Let's Encrypt certificate.

Error message from app is "Incorrect settings"

any advice?

**Comment by Konderi** [comment]
Seems to be issue with 2FA authentication, when i disable that from user it seems to work.
Generates new issue with my android + certificate.
Network error peer not trusted by any of the system trust managers.

**Comment by gajovy** [comment]
I'm unable to help myself, but I just wanted to let you guys know this is still an issue.

**Comment by mhentschke** [comment]
As of right now this is still an issue did anyone get this to work with 2FA? wouldn't like to disable it on my account

**Comment by binsky08** [comment]
Hi,

I'm not sure if it is even possible to include 2FA for API access.
But anyway I have a solution to the problem :)

You need to create a device password!

Go to the user settings -> "Security" and scroll down to "Devices & Sessions".
Enter the app name (or whatever you want), click "Create new app password" and use the generated app password to log in with the Passman app on your device.
![01_generate_device_password](https://user-images.githubusercontent.com/30630233/93004552-4c03f680-f548-11ea-8033-ff2e4f9b610c.png)
![02_copy_password](https://user-images.githubusercontent.com/30630233/93004605-c2085d80-f548-11ea-88b8-37fab3a14850.png)
