### ISSUE TITLE
[FR] Add Single sign-on

### ISSUE THREAD

**Issue by fazlerabbi37** [nextcloud/passman-android#71]
It would be great if you could add single sign-on as an option in addition to the traditional login. This is one of the very few android apps that is not using SSO in the Nextcloud ecosystem.

see more: https://github.com/nextcloud/Android-SingleSignOn

**Comment by DJaeger** [comment]
I placed a $10 bounty on [Bountysource](https://www.bountysource.com/issues/89617789-fr-add-single-sign-on)
