### ISSUE TITLE
Passsman fails to login when TOTP for Nextcloud is activated for a user

### ISSUE THREAD

**Issue by roru69** [nextcloud/passman-android#9]
I have Nextcloud 11.00 with the Passman addon running. When I install TOTP in Nextcloud and activate it for a user, it isn't possible to log into the Passman app, when I deactivate TOTP in Nextcloud, logging into the Passman app is possible again.

Could TOTP for Nextcloud be incorporated in the app?

Kind regards,

RR69

**Comment by brantje** [comment]
You have to use a app password. I don't use 2FA on my cloud, but i'm sure you can find docs about how to generate app passwords.

**Comment by roru69** [comment]
O yes, Missed that. I already use it for the nextcloud app. Thanks for the pointer!

**Comment by brantje** [comment]
No problem =)
